### ISSUE TITLE
Alterar stack order dos squares

### ISSUE THREAD

**Issue by pellizzetti** [Rocketseat/youtube-form-animate-css-js-puro#1]
Vale a pena setar um `z-index` pros squares
```css
.squares li {
  /* ... */
  z-index: -1;
}
```

Assim eles não passam por cima do `form` e não impedem o click (caso estejam passando na frente dos inputs/button).
